language: perl
os: linux
perl:
  - "5.24-shrplib"
script: true
install:
  - echo "Just testing docker on this branch"

after_success:
  - docker build -t $CI_PROJECT_NAME:$TRAVIS_COMMIT .
  - CI_PROJECT_NAME=sneakernet
  - SLUG=$(echo "$TRAVIS_REPO_SLUG" | tr '[:upper:]' '[:lower:]')
  - echo "$CI_PROJECT_NAME"
  - echo $SLUG
  - echo $REPOSITORY_URL
  - echo $TRAVIS_COMMIT
  - echo docker tag $CI_PROJECT_NAME:$TRAVIS_COMMIT $CI_PROJECT_NAME:$TRAVIS_COMMIT
  -      docker tag $CI_PROJECT_NAME:$TRAVIS_COMMIT $CI_PROJECT_NAME:$TRAVIS_COMMIT
  -      docker tag $CI_PROJECT_NAME:$TRAVIS_COMMIT $CI_PROJECT_NAME:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
  - docker push $CI_PROJECT_NAME:$TRAVIS_COMMIT
  - docker push $CI_PROJECT_NAME:latest 


# deploying to dockerhub
#deploy:
#  provider: script
#  script: bash .travis-ci/docker_push
#  on:
#    branch: $TRAVIS_BRANCH

