language: perl
os: linux
perl:
  - "5.24-shrplib"
script: true
install:
  - echo "Just testing docker on this branch"

after_success:
  - CI_PROJECT_NAME=sneakernet
  - docker build -t $CI_PROJECT_NAME:$TRAVIS_COMMIT .
  - SLUG=$(echo "$TRAVIS_REPO_SLUG" | tr '[:upper:]' '[:lower:]')
  - echo "$CI_PROJECT_NAME"
  - echo $SLUG
  - echo $REPOSITORY_URL
  - echo $TRAVIS_COMMIT
  - echo docker tag $CI_PROJECT_NAME:$TRAVIS_COMMIT $SLUG:$TRAVIS_COMMIT
# e.g., docker tag httpd:test fedora/httpd:version1.0.test
  -      docker tag $CI_PROJECT_NAME:$TRAVIS_COMMIT $SLUG:$TRAVIS_COMMIT
  -      docker tag $CI_PROJECT_NAME:$TRAVIS_COMMIT $SLUG:latest
  - echo "$DOCKER_PASSWORD" | docker login --username "lskatz" --password-stdin 
  - docker push $CI_PROJECT_NAME:$TRAVIS_COMMIT
  - docker push $CI_PROJECT_NAME:latest 


# deploying to dockerhub
#deploy:
#  provider: script
#  script: bash .travis-ci/docker_push
#  on:
#    branch: $TRAVIS_BRANCH

