language: perl
perl:
  - "5.24-shrplib"
dist: xenial
sudo: false # faster builds as long as you don't need sudo access
addons:
  homebrew:
    taps: brewsci/bio
    casks:
      - skesa
      - blast
      - mlst
      - prokka
      - kraken
  apt:
    packages:
    - build-essential
    - libberkeleydb-perl
    - bioperl
before_install:
  - export PERL5LIB=$PERL5LIB:$HOME/lib/perl5
  # CGP
  - wget --no-check-certificate https://github.com/lskatz/CG-Pipeline/archive/v0.5.tar.gz
  - tar zxvf v0.5.tar.gz
  - export PATH=$PATH:$(pwd -P)/CG-Pipeline-0.5/scripts
install:
  - wget --no-check-certificate https://ccb.jhu.edu/software/kraken/dl/minikraken_20171019_4GB.tgz
  - tar zxvf minikraken_20171019_4GB.tgz
  # Krona
  #- wget --no-check-certificate https://github.com/marbl/Krona/archive/xl2.5.tar.gz
  #- tar zxvf xl2.5.tar.gz
  #- perl Krona-xl2.5/KronaTools/install.pl -prefix $HOME/krona
  # Configure SneakerNet
  - cp -rv config.bak config
  - sed -i '/KRAKEN_DEFAULT_DB/d' config/settings.conf
  - sed -i '/KRAKENDIR/d' config/settings.conf
  - echo -e "KRAKEN_DEFAULT_DB\t$(pwd -P)/minikraken_20171013_4GB" >> config/settings.conf
  - echo -e "KRAKENDIR\t$HOME/.linuxbrew/bin" >> config/settings.conf
  - sed -i '/KRONADIR/d' config/settings.conf
  - echo -e "KRONADIR\t$HOME/krona/bin" >> config/settings.conf
  - head -n 50 config/*.conf # display configuration file
  - export PATH=$PATH:$(pwd -P)/scripts:$(pwd -P)/SneakerNet.plugins
script: 
  - cpanm --installdeps --notest .
  - perl Makefile.PL
  - make test
