language: perl
perl:
  - "5.24-shrplib"
dist: xenial
addons:
  apt:
    sources:
    - boost-latest
    packages:
    - build-essential
    - file
    - git
    - libboost-all-dev
    - libgdbm-dev
    - expat
    - libberkeleydb-perl
    - openssl
    - bioperl
    - curl
    - ruby2.3-dev
    - rubygems
before_install:
  # CGP
  - export PERL5LIB=$PERL5LIB:$HOME/lib/perl5
  - cpanm -l ~ Statistics::Descriptive
  - cpanm -l ~ File::Slurp
  # double check perl modules
  - perl -MData::Dumper -MFile::Slurp -MStatistics::Descriptive -Mthreads -e 'print Dumper \%INC'
  - wget --no-check-certificate https://github.com/lskatz/CG-Pipeline/archive/v0.5.tar.gz
  - tar zxvf v0.5.tar.gz
  - export PATH=$PATH:$(pwd -P)/CG-Pipeline-0.5/scripts
  - run_assembly_readMetrics.pl --help
  # Homebrew installation
  - export PATH=$PATH:$HOME/.linuxbrew/bin
  - export HOMEBREW_FORCE_VENDOR_RUBY=1
  - git clone https://github.com/Homebrew/brew $HOME/.linuxbrew/Homebrew
  - mkdir $HOME/.linuxbrew/bin
  - ln -s ../Homebrew/bin/brew $HOME/.linuxbrew/bin
  - eval $($HOME/.linuxbrew/bin/brew shellenv)
  - REALLY_GEM_UPDATE_SYSTEM=1 gem update --system
  - gem install activesupport plist backports
  # Screw installing perl and python incorrectly and slowly in brew.
  # Force the system perl and python.
  # PERL
  - mkdir -pv $HOME/.linuxbrew/Cellar/perl/5.28.1/bin
  - ln -sv `which perl` $HOME/.linuxbrew/Cellar/perl/5.28.1/bin
  - brew link perl
  # PYTHON
  - mkdir -p ~/.linuxbrew/Cellar/python@2/2.7.15_1/bin
  - ln -sv `which python` ~/.linuxbrew/Cellar/python@2/2.7.15_1/bin/
  - brew link python@2
install:
  - brew tap brewsci/bio
  - brew install skesa --force-bottle
  - brew install blast --force-bottle
  # mlst prereqs
  - brew install --force-bottle gzip gdbm openssl berkeley-db libbsd expat pkg-config gpatch ncurses gettext libunistring libidn2 readline sqlite util-linux wget
  - brew install mlst
  # prokka prereqs
  - brew install --force-bottle bioperl less aragorn barrnap blast hmmer infernal minced parallel prodigal tbl2asn
  - brew install prokka
  # Configure SneakerNet
  - cp -rv config.bak config
  - export PATH=$PATH:$(pwd -P)/scripts:$(pwd -P)/SneakerNet.plugins
script: 
  - cpanm --quiet --installdeps --notest .
  - perl Makefile.PL
  - make test
