language: perl
perl:
  - "5.24-shrplib"
dist: xenial
addons:
  apt:
    sources:
    - boost-latest
    packages:
    - build-essential
    - file
    - git
    - libboost-all-dev
    #- libboost1.58-dev
    - bioperl
    - curl
    - ruby2.3-dev
    - rubygems
before_install:
  # Homebrew installation
  - export PATH=$PATH:$HOME/.linuxbrew/bin
  - export HOMEBREW_FORCE_VENDOR_RUBY=1
  - git clone https://github.com/Homebrew/brew $HOME/.linuxbrew/Homebrew
  - mkdir $HOME/.linuxbrew/bin
  - ln -s ../Homebrew/bin/brew $HOME/.linuxbrew/bin
  - eval $($HOME/.linuxbrew/bin/brew shellenv)
  - REALLY_GEM_UPDATE_SYSTEM=1 gem update --system
  - gem install activesupport plist backports
  - brew install openssl --force-bottle
  - brew install perl --force-bottle || true # get the perl dependency out of the way
install:
  - brew tap brewsci/bio
  - travis_wait brew install skesa
  - brew install blast --force-bottle
  - brew install mlst
  - brew install prokka
  # CGP
  - wget https://github.com/lskatz/CG-Pipeline/archive/v0.5.tar.gz
  - tar zxvf v0.5.tar.gz
  - export PATH=$PATH:$(pwd -P)/CG-Pipeline-0.5/scripts
  # Configure SneakerNet
  - cp -rv config.bak config
  - export PATH=$PATH:$(pwd -P)/scripts:$(pwd -P)/SneakerNet.plugins
script: cpanm --quiet --installdeps --notest .
