language: perl
perl:
  - "5.24-shrplib"
dist: xenial
sudo: false # faster builds as long as you don't need sudo access
services:
  - docker
addons:
  apt:
    #sources:
    packages:
    - build-essential
    - libberkeleydb-perl
    - bioperl
    - bioperl-run
    - ncbi-blast+
    - prodigal
    - tree
before_install:
  # Docker
  #- docker pull staphb/skesa:2.3.0
  #- docker pull staphb/mlst:2.16.2
  #- docker pull staphb/prokka:1.14.0
  #- docker pull staphb/kraken:1.1.1
  #- export PATH=$PATH:$(pwd)/scripts/dockerAliases
  # Perl modules
  - export PERL5LIB=$PERL5LIB:$(pwd)/lib/perl5
  - export PERL5LIB=$PERL5LIB:$HOME/lib/perl5
  - cpanm -l ~ Statistics::Descriptive
  - cpanm -l ~ File::Slurp
  - tree -d $HOME
  - find $HOME -type f -name Slurp.pm
  - find $HOME -type f -name Descriptive.pm
  - perl -MData::Dumper -MFile::Slurp -MStatistics::Descriptive -Mthreads -e 'print Dumper \%INC'
    #- cpanm -l ~ Bio::FeatureIO --force --notest --verbose # b/c it wasn't getting installed properly somehow with cpanm --installdeps
  # perl debugging statement
  # CGP
  - wget --no-check-certificate https://github.com/lskatz/CG-Pipeline/archive/v0.5.tar.gz
  - tar zxvf v0.5.tar.gz
  - export PATH=$PATH:$(pwd -P)/CG-Pipeline-0.5/scripts
install:
  - wget --no-check-certificate https://ccb.jhu.edu/software/kraken/dl/minikraken_20171019_4GB.tgz
  - tar zxvf minikraken_20171019_4GB.tgz
  # Krona
  - wget --no-check-certificate https://github.com/marbl/Krona/archive/xl2.5.tar.gz
  - tar zxvf xl2.5.tar.gz
  - perl Krona-xl2.5/KronaTools/install.pl -prefix $HOME/krona
  # Configure SneakerNet
  - cp -rv config.bak config
  - sed -i '/KRAKEN_DEFAULT_DB/d' config/settings.conf
  - sed -i '/KRAKENDIR/d' config/settings.conf
  - echo -e "KRAKEN_DEFAULT_DB\t$(pwd -P)/minikraken_20171013_4GB" >> config/settings.conf
  - echo -e "KRAKENDIR\t$HOME/.linuxbrew/bin" >> config/settings.conf
  - sed -i '/KRONADIR/d' config/settings.conf
  - echo -e "KRONADIR\t$HOME/krona/bin" >> config/settings.conf
  - head -n 50 config/*.conf # display configuration file
  - export PATH=$PATH:$(pwd -P)/scripts:$(pwd -P)/SneakerNet.plugins
script: 
  - cpanm --installdeps --notest .
  - perl Makefile.PL
  - make test
