language: perl
os: linux
perl:
  - "5.24-shrplib"
script: true
install:
  - echo "Just testing docker on this branch"

# deploying to dockerhub
deploy:
  provider: script
  script: bash .travis-ci/docker_push
  on:
    branch: $TRAVIS_BRANCH

