# https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: travis-docker
on: 
  push:
    branches:
      - docker-multistage

env:      
  DOCKER_PASSWORD:   ${{  secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME:   lskatz
  #DOCKER_USERNAME:  ${{  secrets.DOCKER_USERNAME }}
  CI_PROJECT_NAME:   sneakernet
  github_repository: lskatz/sneakernet
  SLUG:              ${{ format('lskatz/sneakernet:{0}', ${{ env.GITHUB_SHA }} ) }}
  #LOCAL_TAG_LATEST:  ${{ format('sneakernet:{0}', ${{ env.GITHUB_SHA }} ) }}

jobs:
  init:
    runs-on: ubuntu-18.04
    steps:
      - id:  todo
        run: echo "todo"

  debugging:
    runs-on: ubuntu-18.04
    needs:   init
    steps:
      - id:  print-globals
        run: |
          echo "Docker username starts with ${DOCKER_USERNAME:0:3}..."
          echo "CI_PROJECT_NAME:GITHUB_SHA $CI_PROJECT_NAME:$GITHUB_SHA"
          echo "HOME:$HOME"
          echo "PWD:$PWD"
          echo "GITHUB_WORKSPACE:$GITHUB_WORKSPACE"
          echo "GITHUB_ACTOR/CI_PROJECT_NAME:GITHUB_SHA $SLUG"

  docker_build:
    runs-on: ubuntu-18.04
    needs: init
    steps:
      - uses: actions/checkout@v2
        with:
          ref: docker-multistage
          fetch-depth: 1
      - id:  ls-all-the-things
        run: |
          ls -R $GITHUB_WORKSPACE
          ls -lha $GITHUB_WORKSPACE
      - id:  docker-build
        run: docker build -t $CI_PROJECT_NAME:$GITHUB_SHA $GITHUB_WORKSPACE
      - id:  docker-tag-latest
        run: |
          docker tag $CI_PROJECT_NAME:$GITHUB_SHA $SLUG
      - id:  docker-push-latest
        run: docker push $CI_PROJECT_NAME:$GITHUB_SHA

