name: unit-tests
on: [push]

env:
  spadesVer: 3.14.1
  KRAKEN_DEFAULT_DB: /kraken-database
  PERLLIBDIR: /usr/share/miniconda
# perl: [ '5.32', '5.30', '5.28' ]
# perl: [ '5.32', '5.30.1', '5.16.3', '5.12.3' ]
# os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
# https://github.com/marketplace/actions/setup-perl-environment

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-18.04' ]
        perl: [ '5.26.2' ]
        python: [ '3.7' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - name: add some paths to PATH
        run:  |
          echo "$GITHUB_WORKSPACE/CG-Pipeline/scripts" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/shovill/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/.local/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/krona" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/SPAdes-${spadesVer}-Linux/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/kmc" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/Lighter-1.1.1" >> $GITHUB_PATH
          echo
          cat $GITHUB_PATH
      - name: set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          use-mamba: true
          channels: conda-forge,bioconda,defaults
          mamba-version: "*"
          auto-activate-base: true
          activate-environment: ""
      - name: conda installations
        shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          mamba install -y perl==${{ matrix.perl }} skesa spades krona shovill samclip flash seqtk kmc lighter megahit pilon trimmomatic jellyfish==1.1.12 kraken==1.1.1 perl-app-cpanminus perl-bioperl-run perl-bio-featureio perl-extutils-makemaker perl-local-lib perl-file-slurp
          conda list
      - name: test conda
        shell: bash -el {0}
        run: |
          which conda
          which mamba
          conda info --envs
          shovill --help
          perl -MBio::SeqIO -e 1
          perl -MBio::FeatureIO -e 1
      - name: Get Date
        id: get-date
        run: |
          today=$(/bin/date -u '+%Y%m%d')
          echo $today
          echo "today=$today" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache Conda env
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            steps.get-date.outputs.today }}-${{
            hashFiles('etc/example-environment-caching.yml') }}-${{ env.CACHE_NUMBER
            }}
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
      - name: checkout my repo
        uses: actions/checkout@v2
        with:
          path: SneakerNet
      - name: checkout CG-Pipeline
        uses: actions/checkout@v2
        with:
          repository: lskatz/CG-Pipeline
          path: CG-Pipeline
          ref:  v0.5
      - name: apt-get install
        shell: bash -el {0}
        run:  |
          sudo apt-get update
          sudo apt-get -y install libgd-dev ca-certificates
          #sudo apt-get -y install tree bioperl-run libberkeleydb-perl libdb-dev cpanminus curl 
          sudo apt-get -y install tree curl 
          sudo apt-get -y install build-essential ncbi-blast+ prodigal sendmail 
          # shovill things
          sudo apt-get -y install bwa velvet wget pigz libncurses5-dev libbz2-dev liblzma-dev libfindbin-libs-perl trimmomatic
          # test
          perl -MBio::FeatureIO -e 1
      - name: install minikraken
        shell: bash -el {0}
        run: |
          sudo mkdir -v /kraken-database
          cd /kraken-database
          sudo wget --progress=dot https://ccb.jhu.edu/software/kraken/dl/minikraken_20171101_4GB_dustmasked.tgz
          sudo tar -zxf minikraken_20171101_4GB_dustmasked.tgz
          sudo mv -nv minikraken_20171101_4GB_dustmasked/* . # flatten db dir
          sudo ls -lhSR /kraken-database
      - name: Dumper INC
        shell: bash -el {0}
        run:  perl -MData::Dumper -e 'print Dumper \@INC'
      - name: tree pwd
        shell: bash -el {0}
        run:  tree $(pwd)
      - name: tree home
        shell: bash -el {0}
        run:  tree $HOME
      - name: tree GITHUB_WORKSPACE
        shell: bash -el {0}
        run:  tree $GITHUB_WORKSPACE
      - name: tree -L 3 -d GITHUB_WORKSPACE
        shell: bash -el {0}
        run:  tree -L 3 -d $GITHUB_WORKSPACE
      - run: perl -V
        shell: bash -el {0}
      - name: env
        shell: bash -el {0}
        run:  env
      - name: perl-check-dependencies
        shell: bash -el {0}
        run:  |
          cd $GITHUB_WORKSPACE/SneakerNet
          perl Makefile.PL
          make
          sudo cpanm --installdeps . --verbose --notest --force
          sudo cpanm --verbose --notest --force File::Slurp Statistics::Descriptive Config::Simple Bio::Kmer Text::Fuzzy Email::Stuffer List::MoreUtils Exporter::Tiny

          #cpanm --installdeps . -l ${{ env.PERLLIBDIR }} --verbose --notest --force
          #cpanm -l ${{ env.PERLLIBDIR }} --verbose --notest --force File::Slurp Statistics::Descriptive \
          #  Config::Simple Bio::Kmer Text::Fuzzy Email::Stuffer List::MoreUtils \
          #  Exporter::Tiny
          echo
          perl -MBio::FeatureIO -MBio::SeqIO -MData::Dumper -MStatistics::Descriptive -MConfig::Simple -MFile::Slurp -MBio::Kmer -MText::Fuzzy -MEmail::Stuffer -MMoo -MList::MoreUtils -MJSON -e 'print Dumper \%INC'
          make
          echo "DEBUG: PERL5LIB: $PERL5LIB"
      - name: check-SneakerNet-repo
        shell: bash -el {0}
        run: |
          eval $(perl -I ${{ env.PERLLIBDIR }}/lib/perl5/ -Mlocal::lib)
          cd $GITHUB_WORKSPACE/SneakerNet
          cat MYMETA.json
          echo;env;echo
          ls -lhS t/M00123-18-001-test/
          md5sum t/M00123-18-001-test/*.fastq.gz
          for i in t/M00123-18-001-test/*.fastq.gz; do echo -ne "$i\t"; zcat $i | tail -n 1; done;
          echo
          echo "PATH broken up:"
          echo "$PATH" | tr ":" "\n"
          echo
          echo "GITHUB_ENV: $GITHUB_ENV"
          cat $GITHUB_ENV
          echo "GITHUB_PATH: $GITHUB_PATH"
          cat $GITHUB_PATH
          echo "Which flash:"
          which flash
          echo
          echo "Running t/00_env.t ..."
          perl t/00_env.t
          for i in t/M00123-18-001-test/*.fastq.gz; do echo -ne "$i\t"; zcat $i | tail -n 1; done;
      - id:   prove-lv-t
        name: prove-lv-t
        shell: bash -el {0}
        run:  |
          eval $(perl -I ${{ env.PERLLIBDIR }}/lib/perl5 -Mlocal::lib)
          mkdir -v $GITHUB_WORKSPACE/tmp
          export TMPDIR=$GITHUB_WORKSPACE/tmp
          cd $GITHUB_WORKSPACE/SneakerNet
          sed -i 's+/opt/kraken/full-20140723+/kraken-database+g' config/settings.conf
          #prove -lv t
          make
          make test


